version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod"]

  backend:
    build:
      context: ../app/backend
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      MONGO_URI: mongodb://mongodb:27017/devopsdb
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    restart: always

  frontend:
    build:
      context: ../app/frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  mongo-data:
