# Placeholder PersistentVolumeClaim manifest
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: devops-portfolio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
